Codigo_Maestro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include("home.urls")),
]

handler404 = 'home.views.error_404_view'

home/urls.py
from django.urls import path

from . import views


app_name = 'home'

urlpatterns = [
    path('', views.index, name = "index"),
    path('auth/', views.auth, name="auth"),
    path('details/', views.details, name="details"),
    path('details/comparator/', views.comparator, name="comparator"),
    path('details/common_rankings/', views.rankings, name="rankings"),
    path('details/rating/', views.rating, name="rating"),
    path('details/rating/problems', views.problems, name="problems"),
    path('details/logout/', views.logout, name='logout'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse, HttpResponseRedirect, reverse
import requests, json, time
from operator import itemgetter

access_token = None
api_call_headers = None
username = None
institution =None
usernameR=None


# Create your views here.
# index view
def index(request):
    context = {
        'authorize_url': "https://api.codechef.com/oauth/authorize",
        'token_url': "https://api.codechef.com/oauth/token",
        'callback_uri': "http://127.0.0.1:8000/home/auth/",
        'client_id': <client_id>,
        'client_secret': <client_Secret>,
    }
    if access_token:
        return render(request, "home/details.html", {'example': 'example'})
    else:
        return render(request, "home/index.html", context)

# Authentication purpose
def auth(request):
    global access_token, api_call_headers
    if access_token != None:
        return HttpResponseRedirect(reverse('home:index'))
    authorization_code = request.GET['code']
    headers = {
        'content-type': 'application/json',
    }
    Data = {'grant_type': 'authorization_code', 'code': authorization_code,
            'client_id': "b529d558182948e92f80fa9d2b42b99d",
            'client_secret': "fac9653c2e7dd282bbdd3218fd92e085", 'redirect_uri': "http://127.0.0.1:8000/home/auth/"}
    access_token_response = requests.post("https://api.codechef.com/oauth/token", data=json.dumps(Data),
                                          headers=headers)
    tokens = json.loads(access_token_response.text)
    access_token = tokens["result"]["data"]["access_token"]
    api_call_headers = {'Authorization': 'Bearer ' + access_token}
    return HttpResponseRedirect(reverse('home:details'))


#logout
def logout(request):
    global access_token
    access_token = None
    time.sleep(2)
    return HttpResponseRedirect(reverse('home:index'))

# details page

def details(request):
    global access_token, username, institution,usernameR
    test_url = "https://api.codechef.com/users/me"
    parameters = {
        'fields': 'fullname, country',
    }
    api_call_response = requests.get(test_url, headers=api_call_headers, params=parameters)
    detail_user = json.loads(api_call_response.text)
    username = detail_user["result"]["data"]["content"]["username"]
    rating = detail_user["result"]["data"]["content"]["band"]
    usernameR = rating + ' '+ username
    fullname = detail_user["result"]["data"]["content"]["fullname"]
    institution = detail_user["result"]["data"]["content"]["organization"]

    if access_token:
        return render(request, "home/details.html", {'usernameR': usernameR, 'fullname': fullname, 'detail_user': detail_user, 'username': username})
    else:
        return HttpResponseRedirect(reverse('home:index'))



# for ranking of institution
def rankings(request):
    userrank = None
    contestCode = request.POST["contest"]
    institute= request.POST["institute"]

    question_url = "https://api.codechef.com/contests/" + contestCode
    para = {
        'fields': 'problemsList',
        'sortBy': 'problemCode',
        'sortOrder': 'asc'
    }
    api_call_response = requests.get(question_url, headers=api_call_headers, params=para)
    Questions = json.loads(api_call_response.text)

    if "data" in Questions["result"]:
        queslist = Questions["result"]["data"]["content"]["problemsList"]
    else:
        return render(request, "home/error.html", {'error': 'Fields are wrong. Please check the fields again! '})

    codelist = []
    for i in queslist:
        codelist = codelist + [i['problemCode']]

    ranklist=[]
    userranklist = []
    val = 0
    rankings = None
    length = 1500
    # For general rank list
    while length == 1500:
        dummy = None
        rank_url = "https://api.codechef.com/rankings/" + contestCode
        parameters = {
            'fields': 'username, rank, problemScore, totalScore',
            'institution': institute,
            'offset': val,
            'limit': '1500',
            'sortBy': 'rank',
            'sortOrder': 'asc',
        }

        api_call_response = requests.get(rank_url, headers=api_call_headers, params=parameters)
        rankings = json.loads(api_call_response.text)
        if "content" in rankings["result"]["data"]:
            dummy=rankings["result"]["data"]["content"]
        else:
            return render(request, "home/error.html", {'error': 'cant apply filter to the desired institution'})

        length = len(dummy)
        ranklist = ranklist + dummy
        val = val + 1500


    # For user rank details
    val = 0
    length = 1500
    while length == 1500:
        dummy = None
        rank_url = "https://api.codechef.com/rankings/" + contestCode
        parameters = {
            'fields': 'username, rank, problemScore, totalScore',
            'institution': institution,
            'offset': val,
            'limit': '1500',
            'sortBy': 'rank',
            'sortOrder': 'asc',
        }

        api_call_response = requests.get(rank_url, headers=api_call_headers, params=parameters)
        userrankings = json.loads(api_call_response.text)
        if "content" in userrankings["result"]["data"]:
            dummy = userrankings["result"]["data"]["content"]
        else:
            break
        length = len(dummy)
        userranklist = userranklist + dummy
        val = val + 1500

    for i in userranklist:
        if i['username'] == username:
            userrank = i
            break
    if userrank and institute != institution:
        ranklist = ranklist + [userrank]

    for i in ranklist:
        i['rank'] = int(i['rank'])

    ranklist.sort(key=itemgetter('rank'))


    ranks = []
    users = []
    score = []
    scores = []
    for i in ranklist:
        ranks = ranks + [i['rank']]
        users = users + [i['username']]
        score = score + [i['totalScore']]
        s = []
        for code in codelist:
            flag = 0
            li = i['problemScore']
            for j in li:
                if code == j['problemCode']:
                    s = s + [j['score']]
                    flag = 1

            if not flag:
                s = s + [0]
        scores.append(s)

    data = zip(users, ranks, score, scores)
    data = list(data)
    if access_token:
        return render(request, "home/rankings.html", {'data': data,'username': username, 'institute': institute, 'usernameR': usernameR, 'userrank':userrank, 'codelist': codelist})
    else:
        return HttpResponseRedirect(reverse('home:index'))





#Problems Rating according practice questions

a = []
b = []
c = []
d = []
e = []
f = []
g = []
def problems(request):
    global a,b,c,d,e,f,g
    color = None
    type = request.POST["Value"]
    data_list = []
    if type == "1 Star":
        data_list = a
        color ='#F4F6F6'
    elif type == "2 Star":
        data_list = b
        color = '#EAFAF1'
    elif type == "3 Star":
        data_list = c
        color = '#EAF2F8'
    elif type == "4 Star":
        data_list = d
        color = '#EBDEF0'
    elif type == "5 Star":
        data_list = e
        color = '#FCF3CF'
    elif type == "6 Star":
        data_list = f
        color = '#FDEBD0'
    elif type == "7 Star":
        data_list = g
        color = '#FADBD8'

    data_list.sort(key=itemgetter('successfulSubmissions'), reverse=True)
    if access_token:
        return render(request, "home/problems.html", {'data': data_list, 'type': type, 'color': color, 'code': 'problemCode', 'username':username, 'usernameR':usernameR})
    else:
        return HttpResponseRedirect(reverse('home:index'))



def rating(request):

    global a,b,c,d,e,f,g
    a = []
    b = []
    c = []
    d = []
    e = []
    f = []
    g = []

    question =[]
    questions = "https://api.codechef.com/problems/school"
    parameters = {
        'fields': 'problemCode, problemName, successfulSubmissions, accuracy',
        'offset': 0,
        'limit': 100,
        'sortOrder': 'desc'
    }
    dummy = None

    api_call_response = requests.get(questions, headers=api_call_headers, params=parameters)
    question_list = json.loads(api_call_response.text)

    #if "content" in question_list["result"]["data"]:
    dummy = question_list["result"]["data"]["content"]

    question = question + dummy
    # return HttpResponse(question)

    questions = "https://api.codechef.com/problems/easy"
    parameters = {
        'fields': 'problemCode, problemName, successfulSubmissions, accuracy',
        'offset': 0,
        'limit': 100,
        'sortOrder': 'desc'
    }
    dummy = None

    api_call_response = requests.get(questions, headers=api_call_headers, params=parameters)
    question_list = json.loads(api_call_response.text)

    #if "content" in question_list["result"]["data"]:
    dummy = question_list["result"]["data"]["content"]

    question = question + dummy

    questions = "https://api.codechef.com/problems/medium"
    parameters = {
        'fields': 'problemCode, problemName, successfulSubmissions, accuracy',
        'offset': 0,
        'limit': 100,
        'sortOrder': 'desc'
    }
    dummy = None

    api_call_response = requests.get(questions, headers=api_call_headers, params=parameters)
    question_list = json.loads(api_call_response.text)

    #if "content" in question_list["result"]["data"]:
    dummy = question_list["result"]["data"]["content"]

    question = question + dummy

    questions = "https://api.codechef.com/problems/hard"
    parameters = {
        'fields': 'problemCode, problemName, successfulSubmissions, accuracy',
        'offset': 0,
        'limit': 100,
        'sortOrder': 'desc'
    }
    dummy = None

    api_call_response = requests.get(questions, headers=api_call_headers, params=parameters)
    question_list = json.loads(api_call_response.text)

    #if "content" in question_list["result"]["data"]:
    dummy = question_list["result"]["data"]["content"]

    question = question + dummy

home/templates/home/comparator.html
<!DOCTYPE HTML>

{% load static %}


<html>
	<head>
		<title>Codigo Maestro</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'home/assets/css/main.css' %}">

	</head>

    <style>
        .unique {
        font-size:110%;
    }

	.unique [class^=col-] {
		color:#fff;
		font-weight: 400;
	}

	td{
	    font-weight: 400;
	    color: white;
	    text-align: center;
	}
    th{
    font-size: 2em;
    }
	.unique .col-xs-4, .rate {
	    text-align: center;
	}

    a, h2, h3{
    color: white;
    }

	i{
	font-color: white;
	align: center;
	}

    </style>

	<body style= "background-color:#424949">



        <!-- Navigation bar -->
            <nav class="navbar navbar-inverse">
              <div class="container-fluid">
                <div class="navbar-header" >
                  <a class="navbar-brand" href="{% url 'home:details' %}" style="font-size: 150%; color:white; text-decoration: none;">Codigo Maestro</a>
                    <a class="navbar-brand" href="#" style="font-size: 110%; color:white; text-decoration: none">by coders_sacred</a>
                </div>
                      <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="https://www.codechef.com/users/{{username}}" target="_blank" style="font-size: 110%; color:white; text-decoration: none">Hello! {{usernameR}}</a></li>
                    <li ><a href="{% url 'home:details' %}" style="font-size: 110%; color:white; text-decoration: none">Home</a></li>
                  <li><a href="{% url 'home:logout' %}" style="font-size: 110%; color:white; text-decoration: none"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
                </ul>
              </div>
              </div>
            </nav>


        <div class="container unique" style="background-color: #424242; padding-right: 5%; padding-left: 5%; padding-top: 3%; margin-bottom: 5%; margin-top: 3%;">



            <center><h2> Profile Comparison Result</h2></center>



        <div class="row">
            <div class="col-xs-4" style="font-size:110%">
                <a href="https://www.codechef.com/users/{{ username1 }}" target="_blank" ><b><font color="white">{{ username1 }}</font></b></a>
            </div>
            <div class="col-xs-4">
                vs.
            </div>
            <div class="col-xs-4" style="font-size:110%">
                <a href="https://www.codechef.com/users/{{ username2 }}" target="_blank" ><b><font color="white">{{ username2 }}</font></b></a>
            </div>
        </div>

        <br/>

        <div class="row">
            <div class="col-xs-6" style="padding-left: 4%; ">
                <i>{{ username1 }}</i>'s details:
            </div>
            <div class="col-xs-6" style="padding-left: 8%; ">
                <i>{{ username2 }}</i>'s details:
            </div>
            <div class="col-xs-6" style="line-height:130%; padding-left: 4%; ">
                <i class="fa fa-user-circle-o "></i> {{ fullname1 }} <br>
                <i class="fa fa-briefcase"></i> {{ occupation1 }}, {{ organization1 }} <br>
                <i class="fa fa-map-marker"></i> {{ city1 }}, {{ state1 }}, {{ country1 }}
            </div>
            <div class="col-xs-6" style="line-height:130%; padding-left: 8%; ">
                <i class="fa fa-user-circle-o "></i> {{ fullname2 }} <br>
                <i class="fa fa-briefcase"></i> {{ occupation2 }}, {{ organization2 }} <br>
                <i class="fa fa-map-marker"></i> {{ city2 }}, {{ state2 }}, {{ country2 }}
            </div>
        </div>

<br>

        <div class="row">
            <div class="col-xs-6 " style="padding-left: 4%; ">
                <i>{{ username1 }}</i>'s rating: <span style="font-weight: bold;">{{ current_rating1 }}</span>
            </div>
            <div class="col-xs-6 " style="padding-left: 8%; ">
                <i>{{ username2 }}</i>'s rating: <span style="font-weight: bold;">{{ current_rating2 }}</span>
            </div>
        </div>

        <br/>

        <div class="row">
            <div class="col-xs-12">
                <h3 style="text-align:center"> Common Contests </h3>
            </div>
        </div>

        <table>
            <thead align="center">
            <tr style="background-color:#F2F2F2;">
                <th style="padding:5px; text-align:center"><font color="#424949"><b>{{ username1 }}'s rank</b></font></th>
                <th style="padding:5px; text-align:center"><font color="#F2F2F2">heya</font>  </th>
                <th style="padding:5px; text-align:center"><font color="#424949"><b> {{ username2}}'s rank</b></font></th>
            </tr>
            </thead

            {% if common_ranks %}
                {% for contest, rank1, rank2 in common_ranks %}
                <tr>
                    <td>
                        {{ rank1 }}
                    </td>
                    <td>
                        <a href="https://www.codechef.com/{{ contest }}" target="_blank" >{{ contest }}</a>
                    </td>
                    <td>
                        {{ rank2 }}
                    </td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td>
                        No common contests
                    </td>
                </tr>
            {% endif %}
        </table>


        <br/>

        <div class="row">
            <div class="col-xs-12">
                <h3 style="text-align:center"> Number of Problems Solved </h3>
            </div>
        </div>

        <table>
             <thead align="center">
            <tr style="background-color:#F2F2F2;">
                <th style="padding:5px; text-align:center"><font color="#424949"><b>{{ username1 }}'s count</b></font></th>
                <th style="padding:5px; text-align:center"><font color="#F2F2F2">heya</font>  </th>
                <th style="padding:5px; text-align:center"><font color="#424949"><b> {{ username2}}'s count</b></font></th>
            </tr>
             </thead>
            <tr>
                <td>
                   {{ practice_problems1 }}
                </td>
                <td>
                    Practice Problems
                </td>
                <td>
                    {{ practice_problems2 }}
                </td>
            </tr>

            <tr>
                <td>
                    {{ long_challenge1 }}
                </td>
                <td>
                    Long Challenge
                </td>
                <td>
                    {{ long_challenge2 }}
                </td>
            </tr>

            <tr>
                <td>
                    {{ cook_off1 }}
                </td>
                <td>
                    Cook-Off
                </td>
                <td>
                    {{ cook_off2 }}
                </td>
            </tr>

            <tr>
                <td>
                    {{ lunchtime1 }}
                </td>
                <td>
                    Lunchtime
                </td>
                <td>
                    {{ lunchtime2 }}
                </td>
            </tr>

        </table>


        <br/>


        </div>


	</body>
</html>

home/templates/home/contest_questions.html
{% load static %}

<!DOCTYPE>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'home/assets/css/header.css' %}" />
</head>
<style>

.button {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    padding: 29px 70px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 25px;
    margin: 6px 4px;
    -webkit-transition-duration: 0.4s; /* Safari */
    transition-duration: 0.4s;
    cursor: pointer;
}

.button1 {

    color: white;;
    background-color: #5D6D7E;
    width: 100%;
    margin-left: 0%;
    margin-right: 0%;
}

.button1:hover {
    background-color: white;
    color: black;
    border: 2px solid #5D6D7E;

}

.button2 {
    background-color: #28B463;
    color: white;
    width: 90%;
    margin-left: 5%;
    margin-right: 5%;

}

.button2:hover {
    background-color: white;
    color: black;
    border: 2px solid #28B463;
}

.button3 {
    background-color: #3498DB;
    color: white;
    width: 80%;
    margin-left: 10%;
    margin-right: 10%;
}

.button3:hover {
        background-color: white;
    color: black;
    border: 2px solid #3498DB;
}

.button4:hover {
    background-color: white;
    color: black;
    border: 2px solid #884EA0;
}

.button4 {
    background-color: #884EA0;
    width: 70%;
    margin-left: 15%;
    margin-right: 15%;


}

.button5:hover {
    background-color: white;
    color: black;
    border: 2px solid #F1C40F;
}

.button5 {
    background-color: #F1C40F;
    color: white;
    width: 60%;
    margin-left: 20%;
    margin-right: 20%;
}

.button6:hover {
    background-color: white;
    color: black;
    border: 2px solid #E67E22;
}

.button6 {
    background-color: #E67E22;
    color: white;
    width: 50%;
    margin-left: 25%;
    margin-right: 25%;
}

.button7:hover {
    background-color: white;
    color: black;
    border: 2px solid #C0392B;
}

.button7 {
    background-color: #C0392B;
    color: white;
    width: 40%;
    margin-left: 30%;
    margin-right: 30%;

}
</style>
<body style="background-color: #424949;">



            <nav class="navbar navbar-inverse">
              <div class="container-fluid">
                <div class="navbar-header" >
                  <a class="navbar-brand" href="{% url 'home:details' %}" style="font-size: 150%; color:white; text-decoration: none;">Codigo Maestro</a>
                    <a class="navbar-brand" href="#" style="font-size: 110%; color:white; text-decoration: none">by coders_sacred</a>
                </div>
                      <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="https://www.codechef.com/users/{{username}}" target="_blank" style="font-size: 110%; color:white; text-decoration: none">Hello! {{usernameR}}</a></li>
                    <li ><a href="{% url 'home:details' %}" style="font-size: 110%; color:white; text-decoration: none">Home</a></li>
                  <li><a href="{% url 'home:logout' %}" style="font-size: 110%; color:white; text-decoration: none"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
                </ul>
              </div>
              </div>
            </nav>


<img src="{% static 'home/images/winner.png' %}" alt="" height="16%" width="16%" style="margin-right: 42%; margin-left: 42% ; margin-top: 2em;">

<form action="{% url 'home:problems' %}" method="post" class=center">
    {% csrf_token %}
    <input class="button button7" name="Value" type="submit" value="7 Star"> </input>
    <input class="button button6" name="Value" type="submit" value="6 Star"> </input>
    <input class="button button5" name="Value" type="submit" value="5 Star"> </input>
    <input class="button button4" name="Value" type="submit" value="4 Star"> </input>
    <input class="button button3" name="Value" type="submit" value="3 Star"> </input>
    <input class="button button2" name="Value" type="submit" value="2 Star"> </input>
    <input class="button button1" name="Value" type="submit" value="1 Star"> </input>

</form>
</body>
</html>

home/templates/home/details.html
<!DOCTYPE HTML>


{% load static %}
<html>
	<head>
		<title>Codigo Maestro</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="{% static 'home/assets/css/details.css' %}" />

	</head>
	<style>

		input::-webkit-input-placeholder {
color: red !important;
}

input:-moz-placeholder { /* Firefox 18- */
color: red !important;
}

input::-moz-placeholder {  /* Firefox 19+ */
color: red !important;
}

input:-ms-input-placeholder {
color: red !important;
}


	</style>

	<body id="top">

			<!-- Navigation bar -->
            <nav class="navbar navbar-inverse">
              <div class="container-fluid">
                <div class="navbar-header" >
                  <a class="navbar-brand" href="{% url 'home:details' %}" style="font-size: 150%; color:white; text-decoration: none;">Codigo Maestro</a>
                    <a class="navbar-brand" href="#" style="font-size: 110%; color:white; text-decoration: none">by coders_sacred</a>
                </div>
                      <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="https://www.codechef.com/users/{{username}}" target="_blank" style="font-size: 110%; color:white; text-decoration: none">Hello! {{usernameR}}</a></li>
                    <li ><a href="{% url 'home:details' %}" style="font-size: 110%; color:white; text-decoration: none">Home</a></li>
                  <li><a href="{% url 'home:logout' %}" style="font-size: 110%; color:white; text-decoration: none"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
                </ul>
              </div>
              </div>
            </nav>




			<!-- Main -->

			<!--<div class="blur"></div>-->
				<div id="main" >
					<div class="inner">

					<!-- Boxes -->
						<div class="thumbnails">

							<div class="box">
								<img src="{% static 'home/images/pic01.jpg' %}" alt="" height="48%" width="100%"/>
								<div class="inner">
									<h3>Codechef profile Comparator</h3>
									<p>Ever wondered to compare your Codechef profile with other user at one go? Chef is up with a new feature where you can get all the data at one place.</p>
									<a href="#" class="button fit" id="compare">Let's Compare!</a>
								</div>
							</div>

							<div class="box">
								<img src="{% static 'home/images/pic02.jpg' %}" alt="" height="48%" width="100%"/>
								<div class="inner">
									<h3>Problems sorted on rating basis</h3>
									<p> Ever wished to become an expert in coding? Do it in a systematic way to reach the ultimate 7 star rating from your current rating.</p>
									<a href="{% url 'home:rating' %}" class="button style2 fit">Let's Practice!</a>
								</div>
							</div>

							<div class="box">
								<img src="{% static 'home/images/pic03.jpg' %}" alt="" height="48%" width="100%"/>
								<div class="inner">
									<h3>User-cum-institution ranklist</h3>
									<p>Have you ever tried finding out your position after the contest in the ranklist of some other Institute. If not then you are jsut a button away.</p>
									<a href="#" class="button style3 fit" id="contact">Know Your Standing!</a>

								</div>

							</div>


							<!-- ranking form -->
                          <div id="contactForm">
                              <button id="X" style="position: absolute;
													background: red;
													color: white;
													top: 5px;
													right: 5px;">X</button>
                                <h1><font color="black" size="5px">EAT SLEEP CODE</font></h1>
                                <small><font color="black">Check where you stand in other Institute's ranklist</font></small>

                                    <form action="{% url 'home:rankings' %}" method="post">
                                      {% csrf_token %}
                                      <input  type="text" name="institute" placeholder="Institute's Name" required />
                                      <input  type="text" name="contest" placeholder="contestCode"  required />
                                      <input class="formBtn" type="submit" value="Ranking" />
                                    </form>
                            </div>

                            <!-- compare form -->


                            <div id="contactFormcompare">
                              <button id="Y" style="position: absolute;
													background: red;
													color: white;
													top: 5px;
													right: 5px;">X</button>
                                <h1><font color="black" size="5px">EAT SLEEP CODE</font></h1>
                                <small><font color="black">Compare with the other user</font></small>

                                    <form action="{% url 'home:comparator' %}" method="post">
                                      {% csrf_token %}
                                      <input  type="text"  name="user1" placeholder="Username1"  required />
                                      <input  type="text"  name="user2" placeholder="Username2" required />
										{% if errorc %}
										<h4 style="font-color: black">{{errorc}}</h4>
										{% endif %}
                                      <input class="formBtn" type="submit" value="Compare" />
                                    </form>
                            </div>


						</div>

					</div>

				</div>


		<!-- Scripts -->
			<script src="{% static 'home/assets/js/jquery.min.js' %}"></script>
            <script src="{% static 'home/assets/js/forms.js' %}"></script>
			<script src="{% static 'home/assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'home/assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'home/assets/js/skel.min.js' %}"></script>
			<script src="{% static 'home/assets/js/util.js' %}"></script>
			<script src="{% static 'home/assets/js/main.js' %}"></script>



			<!-- Script for forms -->
<script>
		$( "a#contact" ).click(function() {
			$( "div.box" ).addClass( "blur" );
			$( "div.box" ).addClass( "disabledView" );
		});

		$( "a#compare" ).click(function() {
			$( "div.box" ).addClass( "blur" );
			$( "div.box" ).addClass( "disabledView" );
		});

		$( "button#X" ).click(function() {
			$( "div.box" ).removeClass( "blur" );
			$('#contactForm').fadeToggle();
			 $( "div.box" ).removeClass( "disabledView" );
		});

		$( "button#Y" ).click(function() {
			$( "div.box" ).removeClass( "blur" );
			$('#contactFormcompare').fadeToggle();
			 $( "div.box" ).removeClass( "disabledView" );
		});

</script>

	</body>
</html>

home/templates/home/error_404.html
<html>
  <head>

      <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </head>

  <style>
      body {
    background: #dedede;
}
.page-wrap {
    min-height: 100vh;
}
  </style>
  <body>
    <div class="page-wrap d-flex flex-row align-items-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center">
                <span class="display-1 d-block">404</span>
                <div class="mb-4 lead">The page you are looking for was not found.</div>
            </div>
        </div>
    </div>
</div
  </body>
</html>